config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  mount Sidekiq::Web => '/sidekiq'

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"

  resources :products do
    collection do
      get :search
    end

    resources :comments, only: %i[create destroy] do
      resources :votes, only: %i[create]
    end
    resources :votes, only: %i[create]
  end
  resources :categories
  resources :comments, only: %i[edit update destroy]
end

app/views/partials/_navbar.html.erb
<section class="py-8 px-4 xl:px-10">
  <nav class="relative">
    <div class="flex justify-between items-center">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', size:'250x250' %>
      <% end %>

      <div class="lg:hidden">
        <button class="navbar-burger flex items-center p-3 hover:bg-gray-50 rounded">
          <%= inline_svg_tag('icons/menu.svg', class: 'block h-4 w-4') %>
        </button>
      </div>

      <ul class="hidden absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 lg:flex lg:w-auto lg:space-x-12">
        <li><%= link_to t('shared.links.products'), products_path, class:'text-sm font-medium px-4 py-2 rounded-full hover:bg-gray-100' %></li>
        <li><%= link_to t('shared.links.categories'), categories_path, class:'text-sm font-medium px-4 py-2 rounded-full hover:bg-gray-100' %></li>
      </ul>

      <div class="hidden lg:flex">
        <%= form_with url: search_products_path, method: :get, data: { turbo: true, turbo_stream: true, controller: 'debounce' } do |f| %>
          <%= f.text_field :query, placeholder: t('shared.search'), class: 'px-4 py-3 lg:inline-block text-sm leading-normal font-medium border border-r-0 border-gray-100 rounded-l', data: { action: 'debounce#search' } %>

          <button type="submit" class="px-2 rounded-r border border-gray-100 border-l-0">
            <%= inline_svg_tag('icons/magnifier.svg', class: 'text-gray-300 w-4 h-4') %>
          </button>
        <% end %>
      </div>
    </div>
  </nav>
</section>