config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  mount Sidekiq::Web => '/sidekiq'

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"

  resources :products do
    collection do
      get :search
    end

    resources :comments, only: %i[create destroy] do
      resources :votes, only: %i[create]
    end
    resources :votes, only: %i[create]
  end
  resources :categories
  resources :comments, only: %i[edit update destroy]
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found

  # GET /categories or /categories.json
  def index
    @pagy, @categories = pagy_countless(Category.all, limit: 15)
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    if @category.save
      respond_to do |format|
        flash.now[:success] = t('.success')
        format.html { redirect_to categories_path, success: t('.success') }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    if @category.update(category_params)
      respond_to do |format|
        flash.now[:success] = t('.success')
        format.html { redirect_to categories_path, success: t('.success') }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      flash.now[:success] = t('.success')
      format.html { redirect_to categories_path, success: t('.success') }
      format.turbo_stream
    end
  end

  private

  def handle_record_not_found
    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, alert: t('categories.not_found') }
      format.json { head :no_content }
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_category.html.erb
<%= render Categories::CardComponent.new(category: category) %>

app/views/categories/_form.html.erb
<%= form_with model: category, data: { controller: "form", form_submit_text_value: title } do |f| %>
  <%= render Shared::ModalComponent.new(title:) do |component| %>
    <% if category.errors.any? %>
      <%= component.with_errors_section do %>
        <%= render Shared::ErrorListComponent.new(record: category) %>
      <% end %>
    <% end %>

    <%= component.with_body_section do %>
      <div class="px-10 py-5 space-y-5">
        <div>
          <%= f.label :name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :name, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5', placeholder: t('activerecord.attributes.category.name') %>
        </div>
      </div>
    <% end %>

    <%= component.with_footer_section do %>
      <div class="flex items-center p-4 md:p-5 space-x-3 rtl:space-x-reverse border-t border-gray-200 rounded-b dark:border-gray-600">
        <%= render Shared::Forms::SubmitComponent.new(submit_text: title) %>
        <%= render Shared::Forms::CancelComponent.new(button_name: t('shared.cancel')) %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/categories/create.turbo_stream.erb
<%= turbo_stream.prepend 'categories', @category %>
<%= turbo_stream.update 'modal', '' %>

<%= render_turbo_stream_flash_messages %>

<% if Category.all.count == 1 %>
  <%= turbo_stream.after :modal do %>
    <script>
      window.location.replace("<%= categories_path %>");
    </script>
  <% end %>
<% end %>

app/views/categories/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@category) %>
<%= render_turbo_stream_flash_messages %>

app/views/categories/edit.html.erb
<%= turbo_frame_tag 'modal' do %>
  <%= render partial: 'form', locals: { category: @category, title: t('.edit_category')} %>
<% end %>

app/views/categories/index.html.erb
<% content_for :title, "Categories" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= t('.title') %></h1>
    <%= link_to t('.add_category'), new_category_path, class: 'mb-4 px-6 py-4 text-sm text-white font-semibold bg-red-400 hover:bg-red-300 rounded transition duration-200', data: { turbo_frame: 'modal' } %>
  </div>

  <div id="categories" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @categories.any? %>
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        <%= render collection: @categories, partial: 'category' %>
      </div>
    <% else %>
      <p class="text-center my-10">No categories found.</p>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<%= turbo_frame_tag 'modal' do %>
  <%= render partial: 'form', locals: { category: @category, title: t('.create_category')} %>
<% end %>

app/views/categories/show.html.erb
<%= render Shared::ModalComponent.new(title: @category.name) do |component| %>
  <%= component.with_body_section do %>
    <div class="px-10 py-5 space-y-5 text-black dark:text-white">
      <div>
        <%= @category.name %>
      </div>
    </div>
  <% end %>

  <%= component.with_footer_section do %>
    <%= component.with_footer_section do %>
      <div class="flex items-center p-4 md:p-5 space-x-3 rtl:space-x-reverse border-t border-gray-200 rounded-b dark:border-gray-600">
        <%= link_to t('.edit_category'), edit_category_path(@category), class: 'bg-blue-500 text-white px-4 py-2 rounded-md', data: { turbo_frame: 'modal' } %>
        <%= link_to t('.delete'), category_path(@category), 
            class: 'bg-red-500 text-white px-4 py-2 rounded-md', 
            data: { 
              turbo_method: :delete, 
              turbo_confirm: t('.confirm'),
              action: 'click->shared--modal#hideModal'
            } %>
      </div>
    <% end %>
  <% end %>
<% end %>