config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  mount Sidekiq::Web => '/sidekiq'

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"

  resources :products do
    collection do
      get :search
    end

    resources :comments, only: %i[create destroy] do
      resources :votes, only: %i[create]
    end
    resources :votes, only: %i[create]
  end
  resources :categories
  resources :comments, only: %i[edit update destroy]
end

app/models/concerns/product/categorizable.rb
module Product::Categorizable
  extend ActiveSupport::Concern

  included do
    has_many :product_categories, dependent: :destroy
    has_many :categories, through: :product_categories
    accepts_nested_attributes_for :categories
  end
end

app/models/concerns/product/searchable.rb
module Product::Searchable
  extend ActiveSupport::Concern

  included do
    class << self
      def popular
        joins("LEFT JOIN votes ON votes.votable_id = products.id AND votes.votable_type = 'Product'")
          .select('products.*, COUNT(votes.id) as votes_count')
          .group('products.id')
          .order('votes_count DESC')
      end
    end

    scope :filter_by_name, ->(query) { where('name ILIKE ?', "%#{query}%") }
    scope :visible, -> { where(visible: true) }
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  description :string           not null
#  visible     :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  include Product::Categorizable
  include Product::Searchable
  include Votable
  include Commentable

  has_one_attached :image, dependent: :destroy

  validates :name, :description, presence: true
  validates :name, length: { minimum: 3, maximum: 200 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found

  def index
    # WelcomeJob.perform_later
    @pagy, @products = pagy_countless(Product.popular.visible, limit: 15)
  end

  def search
    @pagy, @products = pagy_countless(Product.filter_by_name(params[:query]), limit: 15)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('products', partial: 'products/search', locals: { products: @products })
      end
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      respond_to do |format|
        flash.now[:success] = t('.success')
        format.html { redirect_to products_path }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @product.update(product_params)
      respond_to do |format|
        flash.now[:success] = t('.success')
        format.html { redirect_to products_path }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      flash.now[:success] = t('.success')
      format.html { redirect_to products_path }
      format.turbo_stream
    end
  end

  private

  def handle_record_not_found
    respond_to do |format|
      format.html do
        flash[:alert] = t('products.shared.not_found')
        redirect_to products_path
      end
      format.turbo_stream do
        flash.now[:error] = t('products.shared.not_found')
        render_turbo_stream_flash_messages
      end
    end
  end

  def set_product
    @product = Product.friendly.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :visible, :image, category_ids: [])
  end

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def simple_description(description, length = 100)
    description.truncate(length)
  end

  def date_format(date, **options)
    options[:format] ||= :default

    I18n.l(date, **options)
  end
end

app/views/products/_form.html.erb
<%= form_with model: product, data: { controller: "form", form_submit_text_value: title } do |f| %>
  <%= render Shared::ModalComponent.new(title:) do |component| %>
    <% if product.errors.any? %>
      <%= component.with_errors_section do %>
        <%= render Shared::ErrorListComponent.new(record: product) %>
      <% end %>
    <% end %>

    <%= component.with_body_section do %>
      <div class="px-10 py-5 space-y-5">
        <div>
          <%= f.label :name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :name, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5', placeholder: t('activerecord.attributes.product.name') %>
        </div>
        <div>
          <%= f.label :description, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_area :description, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5', placeholder: t('activerecord.attributes.product.description') %>
        </div>
        <div>
          <%= f.label :image, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.file_field :image, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
        </div>
        <div class="flex items-center justify-start">
          <%= f.label :visible, class: 'block text-sm font-medium text-gray-900 dark:text-white mr-3' %>
          <%= f.check_box :visible, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5' %>
        </div>

        <div>
          <h2 class="text-lg font-medium text-gray-900 dark:text-white mb-2"><%= t('products.shared.categories_association') %></h2>
          <div class="grid grid-cols-6 gap-2">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
              <%= b.label(class: 'text-gray-900 dark:text-white') {
                b.check_box(class: "border border-teal-500") + b.label(class: 'text-gray-900 dark:text-white ml-2') { b.text }
              } %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <%= component.with_footer_section do %>
      <div class="flex items-center p-4 md:p-5 space-x-3 rtl:space-x-reverse border-t border-gray-200 rounded-b dark:border-gray-600">
        <%= render Shared::Forms::SubmitComponent.new(submit_text: title) %>
        <%= render Shared::Forms::CancelComponent.new(button_name: t('shared.cancel')) %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<%= render Products::CardComponent.new(product: product) %>

app/views/products/_search.html.erb
<%= render partial: 'product', collection: products %>

app/views/products/create.turbo_stream.erb
<%= turbo_stream.prepend 'products', @product %>
<%= turbo_stream.update 'modal', '' %>

<%= render_turbo_stream_flash_messages %>

app/views/products/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@product) %>
<%= render_turbo_stream_flash_messages %>

app/views/products/edit.html.erb
<%= turbo_frame_tag 'modal' do %>
  <%= render partial: 'form', locals: { product: @product, title: t('.edit_product')} %>
<% end %>

app/views/products/index.html.erb
<section class="relative">
  <div class="container px-4 mx-auto mb-16">
    <div class="max-w-3xl mb-14 mx-auto text-center">
      <div>
        <h2 class="mt-8 mb-10 text-4xl font-semibold font-heading"><%= t('.title') %></h2>
      </div>

      <div class="flex items-center justify-end">
        <%= link_to t('.add_product'), new_product_path, class: 'mb-4 px-6 py-4 text-sm text-white font-semibold bg-red-400 hover:bg-red-300 rounded transition duration-200', data: { turbo_frame: 'modal' } %>
      </div>
    </div>

    <%= turbo_frame_tag "products-#{@pagy.page}" do %>
      <div id="products" class="flex flex-wrap -m-3 mb-10">
        <%= render partial: 'product', collection: @products %>

        <%= turbo_frame_tag "products-#{@pagy.next}", src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
      </div>
    <% end %>
  </div>
</section>

app/views/products/new.html.erb
<%= turbo_frame_tag 'modal' do %>
  <%= render partial: 'form', locals: { product: @product, title: t('.new_product')} %>
<% end %>

app/views/products/show.html.erb
<%= render Shared::ModalComponent.new(title: @product.name, data_modal: { controller: 'shared--modal', shared__modal_target: 'modal' }) do |component| %>
  <%= component.with_body_section do %>
    <div class="px-10 py-5 text-black dark:text-white">
      <% if @product.categories.any? %>
        <div><%= t('products.shared.categories_association') %></div>
        <ul class="flex flex-wrap gap-2 space-y-0">
          <% @product.categories.each do |category| %>
            <li>
              <%= render Categories::BadgeComponent.new(name: category.name, color: %w[indigo purple pink blue red green yellow orange brown lime teal cyan fuchsia violet].sample) %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <div class="my-5">
        <%= @product.description %>
      </div>

      <div>
        <%= image_tag @product.image, class: 'w-full h-full object-cover rounded-lg' if @product.image.attached? %>
      </div>

      <div class="text-lg font-medium text-gray-900 dark:text-white mb-4"><%= t('shared.comments.title') %></div>
      <%= turbo_frame_tag 'comments' do %>
        <% if @product.comments.any? %>
          <% @product.comments.sort_by_votes.each do |comment| %>
            <%= render Comments::ItemComponent.new(comment: comment) if comment.persisted? %>
          <% end %>
        <% else %>
          <%= t('shared.comments.no_comments') %>
        <% end %>
      <% end %>
      
      <%= form_with model: @product.comments.new, url: product_comments_path(@product), turbo_frame: 'comments' do |f| %>
        <%= f.hidden_field :comentable_id, value: @product.id %>
        <%= f.hidden_field :comentable_type, value: @product.class.name %>

        <%= f.text_area :message, class: 'w-full p-2 border border-gray-300 rounded-md' %>
        <%= f.submit t('shared.comments.create'), class: 'bg-blue-500 text-white px-4 py-2 rounded-md' %>
      <% end %>
    </div>
  <% end %>

  <%= component.with_footer_section do %>
    <%= component.with_footer_section do %>
      <div class="flex items-center justify-between border-t border-gray-200 dark:border-gray-600">
        <div class="flex items-center p-4 md:p-5 space-x-3 rtl:space-x-reverse rounded-b ">
          <%= link_to t('.edit_product'), edit_product_path(@product), class: 'bg-blue-500 text-white px-4 py-2 rounded-md' %>
          <%= link_to t('.delete'), product_path(@product), 
              class: 'bg-red-500 text-white px-4 py-2 rounded-md', 
              data: { 
                turbo_method: :delete, 
                turbo_confirm: t('.confirm'),
                action: 'click->shared--modal#hideModal'
              } %>
        </div>

        <section class="flex items-center gap-4 my-6 text-white pr-5">
          <div class="flex-shrink-0">
            <%= render Votes::ButtonComponent.new(votable: @product, url: product_votes_path(@product)) %>
          </div>

          <%= turbo_frame_tag "product_#{@product.id}_votes_count" do %>
            <%= t('shared.votes_count', count: @product.votes.count) %>
          <% end %>
        </section>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/products/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@product), @product %>
<%= turbo_stream.update 'modal', '' %>

<%= render_turbo_stream_flash_messages %>